# Generated by Django 3.2.2 on 2021-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, default='', null=True, upload_to='blogImages')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_info', models.CharField(max_length=500)),
                ('blog_date', models.DateField()),
            ],
        ),
    ]
